/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pr3.Vistas;

import java.applet.AudioClip;
import java.util.logging.Level;
import java.util.logging.Logger;
import pr3.Simulacion;

/**
 *
 * @author godof
 */
public class Partida extends javax.swing.JFrame {
    Simulacion s;
    AudioClip audio;
    /**
     * Creates new form Partida
     */
    public Partida(){
        super("HUMANOS VS ZOMBIES VS CAZAVAMPIROS VS VAMPIROS"); 
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/song.wav"));
        audio.loop();
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevoEntorno = new javax.swing.JButton();
        pasarDia = new javax.swing.JButton();
        mostrarDetalles = new javax.swing.JButton();
        avanzar10dias = new javax.swing.JButton();
        invasion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        estadisticas = new javax.swing.JTextArea();
        cglobal = new javax.swing.JButton();
        eglobal = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        acontecimientos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(805, 635));
        getContentPane().setLayout(null);

        nuevoEntorno.setFont(new java.awt.Font("GodOfWar", 0, 24)); // NOI18N
        nuevoEntorno.setText("Crear nuevo entorno");
        nuevoEntorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoEntornoActionPerformed(evt);
            }
        });
        getContentPane().add(nuevoEntorno);
        nuevoEntorno.setBounds(21, 43, 250, 48);

        pasarDia.setFont(new java.awt.Font("GodOfWar", 0, 24)); // NOI18N
        pasarDia.setText("Transcurrir un dia");
        pasarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasarDiaActionPerformed(evt);
            }
        });
        getContentPane().add(pasarDia);
        pasarDia.setBounds(21, 96, 220, 48);

        mostrarDetalles.setFont(new java.awt.Font("GodOfWar", 0, 24)); // NOI18N
        mostrarDetalles.setText("Mostrar detalles");
        mostrarDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarDetallesActionPerformed(evt);
            }
        });
        getContentPane().add(mostrarDetalles);
        mostrarDetalles.setBounds(21, 149, 201, 48);

        avanzar10dias.setFont(new java.awt.Font("GodOfWar", 0, 24)); // NOI18N
        avanzar10dias.setText("Avanzar 10 dias");
        avanzar10dias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avanzar10diasActionPerformed(evt);
            }
        });
        getContentPane().add(avanzar10dias);
        avanzar10dias.setBounds(21, 202, 200, 48);

        invasion.setFont(new java.awt.Font("GodOfWar", 0, 24)); // NOI18N
        invasion.setText("Invasion zombie");
        invasion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invasionActionPerformed(evt);
            }
        });
        getContentPane().add(invasion);
        invasion.setBounds(21, 414, 202, 48);

        estadisticas.setColumns(20);
        estadisticas.setFont(new java.awt.Font("GodOfWar", 0, 24)); // NOI18N
        estadisticas.setRows(5);
        jScrollPane1.setViewportView(estadisticas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(374, 350, 410, 232);

        cglobal.setFont(new java.awt.Font("GodOfWar", 0, 24)); // NOI18N
        cglobal.setText(" Calentamiento global");
        cglobal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cglobalActionPerformed(evt);
            }
        });
        getContentPane().add(cglobal);
        cglobal.setBounds(21, 308, 265, 48);

        eglobal.setFont(new java.awt.Font("GodOfWar", 0, 24)); // NOI18N
        eglobal.setText("Enfriamiento global");
        eglobal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eglobalActionPerformed(evt);
            }
        });
        getContentPane().add(eglobal);
        eglobal.setBounds(21, 361, 238, 48);

        salir.setFont(new java.awt.Font("GodOfWar", 1, 24)); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir);
        salir.setBounds(21, 473, 82, 48);

        acontecimientos.setFont(new java.awt.Font("GodOfWar", 1, 24)); // NOI18N
        acontecimientos.setText("Acontecimientos: ");
        getContentPane().add(acontecimientos);
        acontecimientos.setBounds(21, 271, 324, 32);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 0);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarDetallesActionPerformed
        MostrarDetalles md = new MostrarDetalles(s.mostrarDetalles());
        md.setVisible(true);
    }//GEN-LAST:event_mostrarDetallesActionPerformed

    private void nuevoEntornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoEntornoActionPerformed
        s = new Simulacion();
        s.crearEntorno();  
        estadisticas.setText(s.toString());
        

    }//GEN-LAST:event_nuevoEntornoActionPerformed

    private void avanzar10diasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avanzar10diasActionPerformed
        // TODO add your handling code here:
        s.transcurrirDia(10);
        estadisticas.setText(s.toString());
    }//GEN-LAST:event_avanzar10diasActionPerformed

    private void cglobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cglobalActionPerformed
        s.cambioTemperatura(10);
        estadisticas.setText(s.toString());
    }//GEN-LAST:event_cglobalActionPerformed

    private void eglobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eglobalActionPerformed
        s.cambioTemperatura(-10);
        estadisticas.setText(s.toString());
    }//GEN-LAST:event_eglobalActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.out.println("Cerrando");
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void pasarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasarDiaActionPerformed
        // TODO add your handling code here:
        s.transcurrirDia(1);
        estadisticas.setText(s.toString());
    }//GEN-LAST:event_pasarDiaActionPerformed

    private void invasionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invasionActionPerformed
        s.invasionZombie();
        estadisticas.setText(s.toString());
    }//GEN-LAST:event_invasionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Partida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acontecimientos;
    private javax.swing.JButton avanzar10dias;
    private javax.swing.JButton cglobal;
    private javax.swing.JButton eglobal;
    private javax.swing.JTextArea estadisticas;
    private javax.swing.JButton invasion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mostrarDetalles;
    private javax.swing.JButton nuevoEntorno;
    private javax.swing.JButton pasarDia;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
